/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerDashboardRouteImport } from './routes/manager.dashboard'
import { Route as EmployeeGoalsRouteImport } from './routes/employee.goals'
import { Route as EmployeeDashboardRouteImport } from './routes/employee.dashboard'
import { Route as EmployeeCheckInRouteImport } from './routes/employee.check-in'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminSharedGoalsRouteImport } from './routes/admin.shared-goals'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminHierarchyRouteImport } from './routes/admin.hierarchy'
import { Route as AdminEscalationsRouteImport } from './routes/admin.escalations'
import { Route as AdminCyclesRouteImport } from './routes/admin.cycles'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ManagerTeamEmployeeIdRouteImport } from './routes/manager.team.$employeeId'
import { Route as AdminScorecardEmployeeIdRouteImport } from './routes/admin.scorecard.$employeeId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeGoalsRoute = EmployeeGoalsRouteImport.update({
  id: '/employee/goals',
  path: '/employee/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeCheckInRoute = EmployeeCheckInRouteImport.update({
  id: '/employee/check-in',
  path: '/employee/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSharedGoalsRoute = AdminSharedGoalsRouteImport.update({
  id: '/admin/shared-goals',
  path: '/admin/shared-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHierarchyRoute = AdminHierarchyRouteImport.update({
  id: '/admin/hierarchy',
  path: '/admin/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEscalationsRoute = AdminEscalationsRouteImport.update({
  id: '/admin/escalations',
  path: '/admin/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCyclesRoute = AdminCyclesRouteImport.update({
  id: '/admin/cycles',
  path: '/admin/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTeamEmployeeIdRoute = ManagerTeamEmployeeIdRouteImport.update({
  id: '/manager/team/$employeeId',
  path: '/manager/team/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScorecardEmployeeIdRoute =
  AdminScorecardEmployeeIdRouteImport.update({
    id: '/admin/scorecard/$employeeId',
    path: '/admin/scorecard/$employeeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cycles': typeof AdminCyclesRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/shared-goals': typeof AdminSharedGoalsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/employee/check-in': typeof EmployeeCheckInRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/goals': typeof EmployeeGoalsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/admin/scorecard/$employeeId': typeof AdminScorecardEmployeeIdRoute
  '/manager/team/$employeeId': typeof ManagerTeamEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cycles': typeof AdminCyclesRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/shared-goals': typeof AdminSharedGoalsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/employee/check-in': typeof EmployeeCheckInRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/goals': typeof EmployeeGoalsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/admin/scorecard/$employeeId': typeof AdminScorecardEmployeeIdRoute
  '/manager/team/$employeeId': typeof ManagerTeamEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cycles': typeof AdminCyclesRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/shared-goals': typeof AdminSharedGoalsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/employee/check-in': typeof EmployeeCheckInRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/goals': typeof EmployeeGoalsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/admin/scorecard/$employeeId': typeof AdminScorecardEmployeeIdRoute
  '/manager/team/$employeeId': typeof ManagerTeamEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/profile'
    | '/settings'
    | '/admin/audit'
    | '/admin/cycles'
    | '/admin/escalations'
    | '/admin/hierarchy'
    | '/admin/reports'
    | '/admin/shared-goals'
    | '/auth/callback'
    | '/employee/check-in'
    | '/employee/dashboard'
    | '/employee/goals'
    | '/manager/dashboard'
    | '/admin/scorecard/$employeeId'
    | '/manager/team/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/profile'
    | '/settings'
    | '/admin/audit'
    | '/admin/cycles'
    | '/admin/escalations'
    | '/admin/hierarchy'
    | '/admin/reports'
    | '/admin/shared-goals'
    | '/auth/callback'
    | '/employee/check-in'
    | '/employee/dashboard'
    | '/employee/goals'
    | '/manager/dashboard'
    | '/admin/scorecard/$employeeId'
    | '/manager/team/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/profile'
    | '/settings'
    | '/admin/audit'
    | '/admin/cycles'
    | '/admin/escalations'
    | '/admin/hierarchy'
    | '/admin/reports'
    | '/admin/shared-goals'
    | '/auth/callback'
    | '/employee/check-in'
    | '/employee/dashboard'
    | '/employee/goals'
    | '/manager/dashboard'
    | '/admin/scorecard/$employeeId'
    | '/manager/team/$employeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCyclesRoute: typeof AdminCyclesRoute
  AdminEscalationsRoute: typeof AdminEscalationsRoute
  AdminHierarchyRoute: typeof AdminHierarchyRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSharedGoalsRoute: typeof AdminSharedGoalsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmployeeCheckInRoute: typeof EmployeeCheckInRoute
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeGoalsRoute: typeof EmployeeGoalsRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  AdminScorecardEmployeeIdRoute: typeof AdminScorecardEmployeeIdRoute
  ManagerTeamEmployeeIdRoute: typeof ManagerTeamEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/goals': {
      id: '/employee/goals'
      path: '/employee/goals'
      fullPath: '/employee/goals'
      preLoaderRoute: typeof EmployeeGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/check-in': {
      id: '/employee/check-in'
      path: '/employee/check-in'
      fullPath: '/employee/check-in'
      preLoaderRoute: typeof EmployeeCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shared-goals': {
      id: '/admin/shared-goals'
      path: '/admin/shared-goals'
      fullPath: '/admin/shared-goals'
      preLoaderRoute: typeof AdminSharedGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hierarchy': {
      id: '/admin/hierarchy'
      path: '/admin/hierarchy'
      fullPath: '/admin/hierarchy'
      preLoaderRoute: typeof AdminHierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/escalations': {
      id: '/admin/escalations'
      path: '/admin/escalations'
      fullPath: '/admin/escalations'
      preLoaderRoute: typeof AdminEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cycles': {
      id: '/admin/cycles'
      path: '/admin/cycles'
      fullPath: '/admin/cycles'
      preLoaderRoute: typeof AdminCyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/team/$employeeId': {
      id: '/manager/team/$employeeId'
      path: '/manager/team/$employeeId'
      fullPath: '/manager/team/$employeeId'
      preLoaderRoute: typeof ManagerTeamEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scorecard/$employeeId': {
      id: '/admin/scorecard/$employeeId'
      path: '/admin/scorecard/$employeeId'
      fullPath: '/admin/scorecard/$employeeId'
      preLoaderRoute: typeof AdminScorecardEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCyclesRoute: AdminCyclesRoute,
  AdminEscalationsRoute: AdminEscalationsRoute,
  AdminHierarchyRoute: AdminHierarchyRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSharedGoalsRoute: AdminSharedGoalsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmployeeCheckInRoute: EmployeeCheckInRoute,
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeGoalsRoute: EmployeeGoalsRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  AdminScorecardEmployeeIdRoute: AdminScorecardEmployeeIdRoute,
  ManagerTeamEmployeeIdRoute: ManagerTeamEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
